import reflex as rx
from portfolio.pages.homepage.sections.helper_functions import tag_item
from portfolio.pages.homepage.utilities.languages import LanguageState


def project_section():
    return rx.box(
        rx.heading(
            LanguageState.projects_heading,
            size="8",
            weight="bold",
            color="white",
            margin_bottom="60px",
            text_align="center",
        ),
        rx.box(
            rx.heading(
                LanguageState.projects_diy_title,
                size="6",
                weight="bold",
                color="white",
                margin_bottom="30px",
                text_align="center",
            ),
            rx.box(
                rx.box(
                    rx.image(
                        src="/image.png",
                        width="300px",
                        height="200px",
                        border_radius="15px",
                        object_fit="cover",
                        border="2px solid rgba(255, 255, 255, 0.2)",
                    ),
                    width="320px",
                    display="flex",
                    justify_content="center",
                ),
                rx.box(
                    rx.text(
                        LanguageState.projects_diy_desc,
                        color="rgba(255, 255, 255, 0.9)",
                        size="4",
                        line_height="1.6",
                    ),
                    flex="1",
                    display="flex",
                    align_items="center",
                ),
                display="flex",
                gap="40px",
                align_items="center",
                padding="30px",
                bg="rgba(255, 255, 255, 0.05)",
                border_radius="20px",
                backdrop_filter="blur(10px)",
                border="1px solid rgba(255, 255, 255, 0.1)",
                flex_wrap="wrap",
            ),
            max_width="1000px",
            margin="0 auto 80px auto",
        ),
        rx.box(
            rx.heading(
                LanguageState.projects_dev_title,
                size="6",
                weight="bold",
                color="white",
                margin_bottom="40px",
                text_align="center",
            ),
            rx.box(
                rx.box(
                    rx.image(
                        src="/segmentation.png",
                        width="350px",
                        height="250px",
                        border_radius="15px",
                        object_fit="cover",
                        border="2px solid rgba(255, 255, 255, 0.2)",
                    ),
                    width="370px",
                    display="flex",
                    justify_content="center",
                ),
                rx.box(
                    rx.heading(
                        "Neptun's Eye",
                        size="5",
                        color="white",
                        weight="bold",
                        margin_bottom="15px",
                    ),
                    rx.box(
                        tag_item("Python", "rgba(52, 152, 219, 0.8)"),
                        tag_item("TKinter", "rgba(46, 204, 113, 0.8)"),
                        tag_item("Flask", "rgba(231, 76, 60, 0.8)"),
                        tag_item("ML", "rgba(155, 89, 182, 0.8)"),
                        tag_item("Experiment tracking", "rgba(100, 89, 102, 0.8)"),
                        display="flex",
                        gap="8px",
                        flex_wrap="wrap",
                        margin_bottom="20px",
                    ),
                    rx.text(
                        LanguageState.project_neptun_desc,
                        color="rgba(255, 255, 255, 0.9)",
                        size="4",
                        line_height="1.6",
                    ),
                    flex="1",
                    display="flex",
                    flex_direction="column",
                    justify_content="center",
                ),
                display="flex",
                gap="40px",
                align_items="center",
                padding="30px",
                bg="rgba(255, 255, 255, 0.05)",
                border_radius="20px",
                backdrop_filter="blur(10px)",
                border="1px solid rgba(255, 255, 255, 0.1)",
                margin_bottom="30px",
                flex_wrap="wrap",
            ),
            rx.box(
                rx.box(
                    rx.image(
                        src="/portfolio.png",
                        width="350px",
                        height="250px",
                        border_radius="15px",
                        object_fit="cover",
                        border="2px solid rgba(255, 255, 255, 0.2)",
                    ),
                    width="370px",
                    display="flex",
                    justify_content="center",
                ),
                rx.box(
                    rx.heading(
                        "Portfolio website",
                        size="5",
                        color="white",
                        weight="bold",
                        margin_bottom="15px",
                    ),
                    rx.box(
                        tag_item("Python", "rgba(52, 152, 219, 0.8)"),
                        tag_item("Flask", "rgba(46, 204, 113, 0.8)"),
                        tag_item("Reflex", "rgba(241, 196, 15, 0.8)"),
                        tag_item("Mircoservices", "rgba(231, 76, 60, 0.8)"),
                        display="flex",
                        gap="8px",
                        flex_wrap="wrap",
                        margin_bottom="20px",
                    ),
                    rx.text(
                        LanguageState.project_portfolio_desc,
                        color="rgba(255, 255, 255, 0.9)",
                        size="4",
                        line_height="1.6",
                    ),
                    flex="1",
                    display="flex",
                    flex_direction="column",
                    justify_content="center",
                ),
                display="flex",
                gap="40px",
                align_items="center",
                padding="30px",
                bg="rgba(255, 255, 255, 0.05)",
                border_radius="20px",
                backdrop_filter="blur(10px)",
                border="1px solid rgba(255, 255, 255, 0.1)",
                flex_wrap="wrap",
            ),
            max_width="1200px",
            margin="0 auto",
        ),
        rx.box(
            rx.button(
                LanguageState.ui_github_button,
                on_click=rx.redirect(
                    "https://github.com/Stimm147",
                    is_external=True,
                ),
                bg="rgba(255, 255, 255, 0.1)",
                color="white",
                padding="15px 30px",
                border_radius="25px",
                border="2px solid rgba(255, 255, 255, 0.3)",
                font_size="16px",
                font_weight="600",
                cursor="pointer",
                backdrop_filter="blur(10px)",
                transition="all 0.3s ease",
                _hover={
                    "bg": "rgba(255, 255, 255, 0.2)",
                    "border_color": "rgba(255, 255, 255, 0.5)",
                    "transform": "translateY(-2px)",
                },
            ),
            text_align="center",
            margin_top="60px",
        ),
        padding="80px 20px",
        background="linear-gradient(135deg, rgba(20, 20, 40, 0.95) 0%, rgba(0, 0, 0, 0.9) 50%, rgba(40, 20, 60, 0.95) 100%)",
        backdrop_filter="blur(20px)",
        width="100vw",
        margin_left="calc(-50vw + 50%)",
    )
